### ISSUE TITLE
 Added implementation considering when the L2 chain is closed

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/tokamak-thanos#214]
Looking at the implementation of the pause function, it looks to prevent executing "finalize transactions" when the relayer has a problem.

Therefore, it is not currently considered when the L2 chain is closed.
Considering when the chain is closed, I think the deposit function should also be blocked.
It would be good to add a mechanism to block the deposit function when closing the chain.

**Comment by nguyenzung** [comment]
Thank you

Let discuss it as an improvement that is outside of L2 native token scope.

**Comment by boohyung** [comment]
@Zena-park Thank you for your opinion. The pausability of bridge is designed by Optimism. You can find the reference to https://specs.optimism.io/protocol/superchain-configuration.html#pausability.
They said "The L2 bridge contracts are not pausable, on the basis that issues on L2 can be addressed more easily by a hard fork in the consensus layer."

**Comment by suahnkim** [comment]
@Zena-park 
<img width="765" alt="image" src="https://github.com/user-attachments/assets/ff59db15-a380-4be1-8546-8acc0b60ca4c">

the case you mentioned is not within the scope of Optimism's pause function. As they consider deposit should be still possible, and **pausing should be only used to prevent withdraw issues.** 

The functionality you are requesting is a different feature and will require a different function call other than pause() -> pause() should not be modified, but we should create a different function if you want to add functionality to halt deposit. 

Use case for _"disable deposit"_ 
- if L2 shutsdown, it would be nice if we can disable deposit of ETH and any ERC20 tokens. 
- but this functionality can be easily added when L2 shutsdown because we will upgrade the proxy bridge contract -> I don't think we need to provide this function in the main file 

if you agree with the logic, please close the issue

**Comment by Zena-park** [comment]
Thank you for the detailed explanation.
I will close the issue.
