### ISSUE TITLE
Storage layout doesn't match

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/tokamak-thanos#218]
**Describe the bug**
When comparing the storage layout with Optimism's L1StandardBridge.sol, it doesn't match.

Optimism slot 50
Mainnet L1StandardBridge (https://etherscan.io/address/0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1#code)
```
    {
      "astId": 4171,
      "contract": "src/L1/L1StandardBridge.sol:L1StandardBridge",
      "label": "superchainConfig",
      "offset": 0,
      "slot": "50",
      "type": "t_contract(SuperchainConfig)6776"
    },
```

Our implementation slot 50 and 51
```
    {
      "astId": 16167,
      "contract": "src/L1/L1StandardBridge.sol:L1StandardBridge",
      "label": "systemConfig",
      "offset": 0,
      "slot": "50",
      "type": "t_contract(SystemConfig)22983"
    },
    {
      "astId": 16249,
      "contract": "src/L1/L1StandardBridge.sol:L1StandardBridge",
      "label": "superchainConfig",
      "offset": 0,
      "slot": "51",
      "type": "t_contract(SuperchainConfig)22125"
    }
```

**Configuration**
- Severity: Medium High
based on this resource https://github.com/crytic/slither/wiki/Upgradeability-Checks.

**Impact**
Thanos and OP stack do not have the same storage layout. A future update of Optimism is likely to corrupt the proxy when we are not aware of the storage layout difference.

**Recommendation**
Reverse the order of slots, systemConfig and superchainConfig.

**Exploit Scenario**

**Demo**

**Comment by nguyenzung** [comment]
Thank you @usgeeus 

I think there is no issue here. There are 2 reasons
1. Thanos is a new chain. If we upgrade smart contracts in future, the upgrades will not based on Optimism, it based on Thanos itself. So we don't need to keep the order of storage slots. 
2. When upgrading smart contracts, what we can do it keep all previous variable, and everything will be safe.
3. When talking about issues, issues should be something unexpected, out-of-control and incorrect. Because upgrading is on our control, so it should not be an issue

**Comment by usgeeus** [comment]
Ok thanks, I'm closing this issue
