### ISSUE TITLE
Executing L2CrossDomainMessenger.sendMessage multiple times without TON.transferFrom results in loss of funds

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/tokamak-thanos#243]
**Describe the bug**
If you execute the L2CrossDomainMessenger.sendMessage function multiple times as shown below, only the last requested amount3 can be withdrawn, and amount1 and amount2 are locked in L1CrossDomainMessenger.

L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: amount1 })
L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: amount2 })
L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: amount3 })

**Configuration**

Severity: Critical

**Impact**

Loss of funds

**Recommendation**
When approving, you should not reduce the existing allowance value.

https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L305

https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L309

**Comment by nguyenzung** [comment]
Could you explain more the scenario that users lose token? @Zena-park 

We need this line because if the message is not relayed successfully, an users can try again. If we dont reset the approval amount, users can take this token with a failed relay and still can relay the message again   https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L309 

And each withdrawal transaction has it own versionHash, and it makes sure that every withdrawal can be called: https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L253

**Comment by Zena-park** [comment]
If L1Wallet executes (1), (2), (3) below in order,
(1) 
`L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: 30 })`
After finalizing,
`ton.allowance(L1CrossDomainMessenger, L1Wallet)` is 30

(2) 
`L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: 20 })
`After finalizing,
`ton.allowance(L1CrossDomainMessenfer, L1Wallet) ` is 20
**I expect it should be 50 because there is something sent in (1) above.**

(3) 
`L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: 10 })`
After finalizing,
`ton.allowance(L1CrossDomainMessenfer, L1Wallet)` is 10
**I expect it should be 60 because there is something sent in (1)and (2) above.**

Finally, L1Wallet sent 30, 20, 10 from L2 and finished finalizing, and then L1Wallet wants to get the TON from L1CrossDomainMessenger at once. 

`ton.transferFrom(L1CrossDomainMessenfer, L1Wallet, 60)` Can the transaction succeed?

**Comment by nguyenzung** [comment]
Thank you @Zena-park 

But it is an expected behavior. We already have tested related to this case: https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/test/L1CrossDomainMessenger.t.sol#L506

Not only for your case, the target of the relayMessage is desgined to be a contract address, not EOA. Beside, the target should trigger transferFrom to collect token. Otherwise, the token will be kept in the CDM.

**Comment by zzooppii** [comment]
It is critical according to our codeReview criteria
Because there are cases where funds can be locked.

However, the call from L2CrossDomainMessenger is not what we want, so if the user intended to lock the funds, it is not critical.

I think it can be modified like this: https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/OptimismPortal.sol#L357-L360
.

Does this modification cause another problem?

**Comment by nguyenzung** [comment]
This thing is expected before. There is also another e2e test for this case: https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/op-e2e/e2e-dep-with/cross_domain_messenger_test.go#L22. 
So I think it can not be considered an issue. 

The proposal solution has a problem so that I did not implement it like what is implemented in the OptimismPortal. 
The reason is users can relayMessage multiple time if the message was not relayed successfully. In this case, if the approval amount is not reset, users can leverage a failed relayMessage to take every TON in L1CDM.

**Comment by mehdi-defiesta** [comment]
After quickly reviewing the relayMessage function, here are my thoughts: 
https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L311
```Solidity
IERC20(_nativeTokenAddress).approve(_target, 0);
```
should be replaced by 
```Solidity
uint256 currentAllowance = IERC20(_nativeTokenAddress).allowance(address(this), _target);
IERC20(_nativeTokenAddress).approve(_target, currentAllowance - _value);
```
So that the user can still withdraw past transaction eventhough the current call fails.

https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L307

```Solidity
IERC20(_nativeTokenAddress).approve(_target, _value);
```
should be replaced by 
```Solidity
uint256 currentAllowance = IERC20(_nativeTokenAddress).allowance(address(this), _target);
IERC20(_nativeTokenAddress).approve(_target, currentAllowance + _value);
```

@nguyenzung I did not really understood your last message but I'll try to check your test suite to verify you did not forgot any parameter and if I see any, I'll write a PoC.

**Comment by zzooppii** [comment]
I also think changing it as Mehdi suggested would be a way to avoid locking the funds.

However, we need to think carefully about making the change because we don't know what the consequences will be.

**Comment by nguyenzung** [comment]
Thank you for your opinion @mehdi-defiesta @zzooppii 

We should notice that the initial approval amount is 0 for every target address. 

And there are 2 places where the function approve is used in L1CDM
- In the function _sendNativeTokenMessage(). The approval amount will be clear later when L1CDM call OptimismPortal.depositTransaction
- In the function relayMessage: For every time this function is called, the approval amount for the target address does not change, because just increase approval amount by _value and then decrease approval amount by _value. It is also possible that function will be reverted with overflow error when the decrease operator runs because currentAllowance could be 0. So that, after this function is executed, the approval amount is still 0 as the initial approval value.
```
uint256 currentAllowance = IERC20(_nativeTokenAddress).allowance(address(this), _target);
IERC20(_nativeTokenAddress).approve(_target, currentAllowance + _value);
...
uint256 currentAllowance = IERC20(_nativeTokenAddress).allowance(address(this), _target);
IERC20(_nativeTokenAddress).approve(_target, currentAllowance - _value);
```

**Comment by nguyenzung** [comment]
I think it is a good finding https://github.com/tokamak-network/tokamak-thanos/issues/229

It can solve some cases. However, I think if users want to bridge token, they can ignore using L2CrossDomainMessenger.sendMesasge().

**Comment by mehdi-defiesta** [comment]
thanks @nguyenzung for the clarification. 
**Regarding the first point**: the approval in _sendNativeTokenMessage does not concern the _target but the OptimismPortal => it does not impact the user token transfer power. 
**Regarding the second point**: I see your point but here we are talking the case where user sendMessage from L2CDM multiple time without transferFrom directly. By doing so the user might not be able to self transfer the total of native token he bridged from L2 to L1 through these multiple sendMessage calls. 
I'll try to right some tests for that and let's see what other people think about it

**Comment by NegruGeorge** [comment]
This scenario might occur when the _target is an EOA and not a Smart Contract: 
```
L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: 30 })
After finalizing,
ton.allowance(L1CrossDomainMessenger, L1Wallet) is 30
(2)
L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: 20 }) After finalizing,
ton.allowance(L1CrossDomainMessenfer, L1Wallet)  is 20
I expect it should be 50 because there is something sent in (1) above.
(3)
L2CrossDomainMessenger.sendMessage(L1Wallet.address, '0x', 200000, { value: 10 })
After finalizing,
ton.allowance(L1CrossDomainMessenfer, L1Wallet) is 10
```


In this line:
```
bool success = SafeCall.call(_target, gasleft() - RELAY_RESERVED_GAS, 0, _message);
```
When the _target is an EOA, the SafeCall.call function will always return success = true because EOAs do not process calldata (_message), the transaction doesn't revert; it simply doesn't execute anything because EOAs don't have associated code to process or interpret the calldata. This means that the function call does not actually perform any action, but the approval for the tokens is still reset. As a result, each call to `relayMessage` function with an EOA as _target will reset the allowance, potentially leading to locked funds since no transfer occurs.

In contrast, when _target is a smart contract, the SafeCall.call function will execute the calldata (_message), which should contain a transferFrom call or similar logic to transfer the tokens from the L1CrossDomainMessenger by the _target  to the intended recipient. After this transfer, the approval is reset, ensuring that the tokens are not locked and are correctly transferred.



Another solution to prevent this issue might be to introduce a restriction that the _target must be a smart contract, not an EOA. This can be enforced by adding a require statement to check if _target is a contract.

Question. Do we have a scenario where _target should be an EOA ? if not, we can restrict it. 
( Please correct me if I am wrong ). 
What do you think ?

**Comment by mehdi-defiesta** [comment]
Actually even if _target is an EOA, the call is made by the L1CrossDomainMessenger contract and it will always process the calldata :
```Solidity
assembly {
    _success :=
        call(
            _gas, // gas
            _target, // recipient
            _value, // ether value
            add(_calldata, 32), // inloc
            mload(_calldata), // inlen
            0, // outloc
            0 // outlen
        )
}
```

We should try to test the following scenario: 
1) user A calls ```initiateWithdrawal``` from L2ToL1MessagePasser with a value > 0 and a message that does not transfer any token on L1 (we assume user A wants to do it manually).
2) user B calls ```initiateWithdrawal``` from L2ToL1MessagePasser with a value > 0 but with a message that calls a reverting function.
=> allowance is set to 0 user A is not able to transfer his native token anymore.

The probability of this scenario could be high if the ecosystem incentivizes users to bridge native token to L1 without using the L2StandardBridge. Moreover, a malicious user could MEV the pool of transaction to DOS the entire ecosystem (probability not high as this user would spend consequent amount to make it happen).

For me this is definitely an issue with a **Medium/High** severity. My recommendation above would mitigate the issue.

**Comment by NegruGeorge** [comment]
Thank you for pointing that out. You are right; my previous assumption was incorrect.

**Comment by nguyenzung** [comment]
Thank you for your interesting opinions @NegruGeorge @mehdi-defiesta 

If we support the case that a target can be an EOA, it will be weird because why we need to send messages to EOAs?

The purpose of the relayMessage function is executing a target address that includes transferFrom logic inside with prior approval amount. So the consequence are:
1. The target is a contract address with the logic of handling messages contains a transferFrom() call
2. Relay a message with the correct approval amount, so we can not increase the approval amount. If approval amount increases cumulatively, it does not satisfy the purpose of the message and also make some other messages can not be relayed successfully. 
3. Reset the approval amount is to 0, specially when the message was relayed failed, if not hackers can take all L2 native token from L1CDM (If a message is relayed failed, an user can relay the message again)

So we can't support bridging token by using EOAs as targets with L2CrossDomainMessenger.sendMessage()

**Comment by suahnkim** [comment]
call log 9.3

https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L260-L262

need to recheck this area (will elaborate)

**Comment by suahnkim** [comment]
call log 9.3 v2
https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L303-L310
need to decide which direction to go 
- should support atomic transaction of asset movement and the call message

**Comment by suahnkim** [comment]
call log 2024.9.3 [L2 native token issue 243](https://github.com/tokamak-network/tokamak-thanos/issues/243), @suahnkim @Zena-park @zzooppii @boohyung @rlgns98kr 

-   asked some clarification on replayability for replayMessage -> assumed that replayability was not possible, but Steven clarified that when message is being replayed the call has to happen [Not from messenger address](https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L257). So, there is no issue
-   gave comment about how Optimism's version of Optimism Portal does not transfer token to L1crossDomainMessenger, but [l2 native token code does](https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L262C1-L263C1) -> Steven clarified that L2 native token code wanted to emulate the ETH movement by making l2 native token movement.

-   Suah: Please note that transfer code **doesn't actually have to live in L1crossDomainMessenger **and can live on Optimism portal code (because ETH movement starts from Optimism Portal, in Optimism version)

-   Finally, regarding the [approve function in L1CrossDomainMessenger](https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L303-L310),

-   it is not a good UX to guide developers to make sure to include transfer logic within the call -> this is not an expected behavior from Optimism's version of Optimism Portal code. ETH is transferred with the success of the Call.** If we do not patch this, we will need to include lengthy warning on what not to do in the code and developer guide (not very pleasant)**

-   to emulate Optimism's version's behavior, this part of the code should be atomic: the call has to be successful and the transfer (not approve) should be successful at the same time. For all other cases, the transfer should fail. This can be achieved either using assembly (there are well known examples that you can reuse) or other method
-   Adding approval logic seem to create many check points that were not previously considered before, it maybe better to try to emulate Optimism's flow -> atomically transfer the L2 native token when message called is successful

-   the current UX can in fact lock TON in L1CrossDomainMessenger due to approve error as explained in the issue -> this is actually not acceptable outcome as L1CrossDomainMessenger is a low level API.

-   the current code has issue when the target is contract -> this reduces functionality of the code, as they have to ensure that the transfer happens on top of their code

-   It is important to create our own code, however there are some UX we should try to keep from Optimism's version to** reduce confusion for the developers**.
-   This seems to be an important point that distinguishes between Optimism's custom gas token implementation from ours -> probably should include this part in details in spec document.

Resolution

-   @rlgns98kr will think about how to resolve the issue and discuss with internal members

**Comment by nguyenzung** [comment]
I think we can check this doc. https://docs.optimism.io/builders/app-developers/bridging/messaging
There is a part to explain about the purpose of CrossDomainMessenger and explain about the parameters

![Screenshot from 2024-09-04 22-27-49](https://github.com/user-attachments/assets/3837ee5d-d17e-41a4-b303-8728c396dc7e)

The scenario uses EOA for target address. So we can consider it is the sender's mistake.

**Comment by suahnkim** [comment]
call log 2024.9.4

**Discussed issues with resetting approve amount**
- Brave: explained that it is not part of normal usage and we do not need to worry about this usage
- Suah: explained that by opening up possibility of partially or none of approve amount during the call, it opens up a way for developers to use it without understanding the core issue -> leading to attacks like resetting approve amount

**Discussed possible paths**
- use the current version (with replacing safeIncreaseAllowance with safeTransfer on Optimism portal)
  - but this seems like a risky path and has issue with developer experience as it is very different from Optimism's flow (explained more below)
- update the L1crossDomainMessenger to mimic Optimism's ETH flow from OptimismPortal
  - this seems like an impossible task that could have more unintended behavior
- update the L1crossDomainMessenger and OptimismPortal to follow Optimism's custom gas token logic for L2 native token, where L1crossDomainMessenger is not intended to be used
  - this will reduce the uniqueness of our code, other than the fact that we have depositTransaction specific for L2 native token (as opposed to reserved for ETH only in Optimism)
  
**Discussed issue with usage of approval in L1crossDomainMessenger**
- Suah: many attacks in ethereum smart contract originates with issues with approval
in our code, approval of assets owned by L1crossDomainMessenger is given to an arbitrary target contract, and this seems like a dangerous logic we are opening up.
  - As long as the assets are bounded (i.e., no rentry issue -> contract team already checked that there is no reentry issue), we should be theoretically safe, but this is undoubtedly dangerous if the assets are not bounded
  
**Current implementation's replayMessage flow assumes that the target contract will have to call transfer of TON in addition to any logic** 
- this deviates from Optimism's replayMessage, where ETH (or custom gas Token) is sent automatically and do not have to include this logic
- this will make existing Ethereum based contract code porting to Thanos or L2 on demand code based on Thanos, much more complex as they have to ensure that the TON transfer logic is always included when they send message from L2 to L1
- Also we need to include more detailed explanation about this part in documentation and code interface to reduce unintended actions

**Resolution**
- We should check in with the foundation on which path to take

**Comment by suahnkim** [comment]
@nguyenzung 
to close this issue:
Please add appropriate warning in the [relevant code](https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L303)
  - About how L2 Native Token transfer logic needs to be included as _message 
  - About how _target should not be EOA as it could lead to loss in fund
- please include this part in the spec documentation 

Reasons for including the warning in the code:
- Even though Optimism does not have this warning in their code, I think it is **helpful** for the developers who is building functions based on L1CrossDomainMessenger.  

With regarding the thread about which path to take, I will start a new thread, so that it is not confusing.

**Comment by zzooppii** [comment]
I think that solving this problem is the best way, but if solving this problem leads to other problems.
it is also good to follow the conclusions made in the TOP project.

I think it is very important to inform about this risk through comments.

**Comment by nguyenzung** [comment]
Hi @suahnkim  @Zena-park @nguyenzung 

i added some comments and changed a condition checking: https://github.com/tokamak-network/tokamak-thanos/commit/977cc5286f7568d07addfbc1eae879d9fd2a7abf

**Comment by Zena-park** [comment]
Okay.  
I will close the issue.
