### ISSUE TITLE
Missing check `successfulMessages[versionedHash]` after the external call succeeds

### ISSUE THREAD

**Issue by 0x6e616d** [tokamak-network/tokamak-thanos#254]
Related to [this issue](https://github.com/ethereum-optimism/optimism/pull/8864) from OP, we should check `successfulMessages[versionedHash]` must be false before setting it to be true(when the external call succeeds)

In [CrossDomainMessenger.relayMessage](https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L290), we already included it. But we override [relayMessage](https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L314) on L1CrossDomainMessager and missed it

- CrossDomainMessenger.sol:
```solidity
// 
if (success) {
      // This check is identical to the one above, but it ensures that the same message cannot be relayed
      // twice, and adds a layer of protection against reentrancy.
      assert(successfulMessages[versionedHash] == false);
      successfulMessages[versionedHash] = true;
      emit RelayedMessage(versionedHash);
}
```

L1CrossDomainMessager.sol
```solidity
 if (success) {
          successfulMessages[versionedHash] = true;
          emit RelayedMessage(versionedHash);
}
```
-> Suggestion changes
```solidity
 if (success) {
      assert(successfulMessages[versionedHash] == false);
      successfulMessages[versionedHash] = true;
      emit RelayedMessage(versionedHash);
}
```

**Comment by suahnkim** [comment]
Any idea how this was missed? 

Or was it purposefully left out?

**Comment by 0x6e616d** [comment]
> Any idea how this was missed? Or was it purposefully left out?
> 
> The reason why I asked is to figure out if we need to check other overridden functions.

Because we added the override function and didn't know this issue -> we assumed that this condition was already checked at [line 273.](https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L273)

But this is a different issue, so it would be good to add it now.

**Comment by nguyenzung** [comment]
I understood this attack scenario. 
I removed it because i thought that it is useless. This scenario is really complex because it relates to upgrading process. I will update the code. 
Thank you, @0x6e616d

**Comment by nguyenzung** [comment]
I think the code is still safe because there is other protection: https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L365

But I think still need to add a check

**Comment by 0x6e616d** [comment]
> I think the code is still safe because there is other protection: https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L365
> 
> But I think still need to add a check

Yes, this issue is resolved by:
- Do not over the xDomainMsgSender if it is not the default value.
- Add another check that `successfulMessages` for the message is still false after the
external call. 

-> We added point 1, with point 2, we already added it on the XDM contract, so but with L1XDM, we overrode `relayMessage` function, so we still need to add the check

**Comment by nguyenzung** [comment]
Thank you, @0x6e616d 

I updated: https://github.com/tokamak-network/tokamak-thanos/commit/f4ecf1c906a36faa5eac05104f935b92eaa69658

As I understood, there was an error with Optimism when they upgraded their contract with their multi-signatures solution as what described here: https://github.com/ethereum-optimism/optimism/pull/8864. It does not happen with our case even if there is no updates because we are not using multi-signatures. But It is better for update the code here

With Optimism's multi-signature policy, attackers can try to make reentrancy attacks the function relayMessage when having enough vote for upgrading.

About the first solution: Do not over the xDomainMsgSender if it is not the default value.
1. Call relayMessage function
2. At  the line https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L307, there is a call to upgrade the contract, after finishing the upgrade process, there is a sub call to relayMessage again with the same message
3. The Optimism fixed the attack line 369-371 (called when upgrading) https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L367
- **Without this fix, xDomainMsgSender = Constants.DEFAULT_L2_SENDER and it is possible for a reentrancy call**
5. Call the relayMesasge with the same message
- This time, the reentrancy check works : https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L286

About the first solution: Added another check that successfulMessages for the message is still false after the
external call.
This solution does not prevent reentrancy attack, however still solve the issue
1. Call the relayMessage the first time
2. When running to the [line](https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L307) call upgrade and relayMessage with same message
3. The reentrancy call is successful, and  **successfulMessages[versionedHash] = true;**
4. Return to the first relayMessage call
- The first call will be failed by the check:  **assert(successfulMessages[versionedHash] == false);**
So for the second solution, the problem is solved, but the reentrancy call is successful while the first call is failed.

**Comment by 0x6e616d** [comment]
> Thank you, @0x6e616d
> 
> I updated: [f4ecf1c](https://github.com/tokamak-network/tokamak-thanos/commit/f4ecf1c906a36faa5eac05104f935b92eaa69658)
> 
> As I understood, there was an error with Optimism when they upgraded their contract with their multi-signatures solution as what described here: [ethereum-optimism/optimism#8864](https://github.com/ethereum-optimism/optimism/pull/8864). It does not happen with our case even if there is no updates because we are not using multi-signatures. But It is better for update the code here
> 
> With Optimism's multi-signature policy, attackers can try to make reentrancy attacks the function relayMessage when having enough vote for upgrading.
> 
> About the first solution: Do not over the xDomainMsgSender if it is not the default value.
> 
> 1. Call relayMessage function
> 2. At  the line https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L307, there is a call to upgrade the contract, after finishing the upgrade process, there is a sub call to relayMessage again with the same message
> 3. The Optimism fixed the attack line 369-371 (called when upgrading) https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/universal/CrossDomainMessenger.sol#L367
> 
> * **Without this fix, xDomainMsgSender = Constants.DEFAULT_L2_SENDER and it is possible for a reentrancy call**
> 
> 4. Call the relayMesasge with the same message
> 
> * This time, the reentrancy check works : https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L286
> 
> About the second solution: Added another check that successfulMessages for the message is still false after the external call. This solution does not prevent reentrancy attack, however still solve the issue
> 
> 1. Call the relayMessage the first time
> 2. When running to the [line](https://github.com/tokamak-network/tokamak-thanos/blob/codeReview/packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol#L307) call upgrade and relayMessage with same message
> 3. The reentrancy call is successful, and  **successfulMessages[versionedHash] = true;**
> 4. Return to the first relayMessage call
> 
> * The first call will be failed by the check:  **assert(successfulMessages[versionedHash] == false);**
>   So for the second solution, the problem is solved, but the reentrancy call is successful while the first call is failed.  => the whole transaction is failed

Thank you! Sound goods
