### ISSUE TITLE
Remove calling paused method in L2StandardBridge

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-thanos#271]
L2StandardBridge uses StandardBridge's pause method. But the method returns `false` always. Therefore, calling paused method in L2StandardContract makes no sense.

#### Code lines to remove
https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/contracts-bedrock/src/L2/L2StandardBridge.sol#L104
https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/contracts-bedrock/src/L2/L2StandardBridge.sol#L135

#### StandarBridge's paused method
https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/contracts-bedrock/src/universal/StandardBridge.sol#L166

**Comment by nguyenzung** [comment]
We are following the Optimism's solution. Optimism's code is the same this point.

**Comment by blackcow1987** [comment]
@nguyenzung This answer is not enough. All code should have meaning. If optimism is doing it, then the meaning should be shared. If not, then it is unnecessary code and should be considered for removal.

**Comment by nguyenzung** [comment]
@blackcow1987 I agreed that my answer was not enough, because to be honest, I also don't understand why they implement it like that. However, Thanos is a fork based on Optimism with the L2 native token feature, so we try to keep everything the same as Optimism's code except what we need to modify to support the L2 native token feature

**Comment by ohbyeongmin** [comment]
@nguyenzung 
In my opinion, it should be fine to delete this code. In the case of Optimism, the paused() function is used because the finalizeBridgeETH code implemented in the StandardBridge contract is inherited and used on both L1 and L2. However, in the case of Thanos, since the finalizeBridgeETH function is overridden, this code can be deleted in L2StandardBridge. Additionally, as noted in the comment for the paused() function, since it is not used on L2, deleting it can still be considered as maintaining the same structure as Optimism.

**Comment by nguyenzung** [comment]
@ohbyeongmin 
I think it makes sense. Thank you!

**Comment by theo-learner** [comment]
@blackcow1987 Can I close this issue?
