### ISSUE TITLE
Remove unnecessary require statement from finalizeBridgeNativeToken method in L2StandardBridge contract

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-thanos#272]
The finalizeBridgeNativeToken method starts out like this:
https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/contracts-bedrock/src/L2/L2StandardBridge.sol#L107

```
    function finalizeBridgeNativeToken(
        address _from,
        address _to,
        uint256 _amount,
        bytes calldata _extraData
    )
        public
        payable
        override
        onlyOtherBridge
    {
        require(paused() == false, "StandardBridge: paused");
        require(msg.value == _amount, "StandardBridge: amount sent does not match amount required");
        require(_to != address(this), "StandardBridge: cannot send to self");
        require(_to != address(messenger), "StandardBridge: cannot send to messenger");
```

I think it is unnecessary to check whether the _to is messenger. The reason is that when calling Safe.call, It does not set msg.data, so there is no need to check _to if the target of the call does not implement a meaningful receive method.
```
        bool success = SafeCall.call(_to, gasleft(), _amount, hex"");
        require(success, "StandardBridge: Native token transfer failed");
```

**Comment by nguyenzung** [comment]
I think it is better if we have a check for _messenger because
1. If we allow _messenger, the token flow can be: XDM -> L2StandardBridge -> XDM: it wastes gas. It is better if the function reverts and the flow is XDM -> L2StandardBridge(revert)
2. The Optimism team does the same thing.

**Comment by blackcow1987** [comment]
@nguyenzung 
Sending native tokens (TON) to messengers is not common, and I think most people don't interface directly with contracts, but rather use a bridge frontend, so I think this is a waste. If the code doesn't cause serious defects(or vulnerability), I think it's better to consider most common cases rather than one bad case.

**Comment by nguyenzung** [comment]
I got your point. It is a valuable opinion.
I think it is possible that there are parts we don't understand fully, so that why we keep the Optimism's logic as much as possible, just modified what we must change. We are also doing an audit. We will check other opinions about that.

**Comment by theo-learner** [comment]
Hi @blackcow1987. Sorry for the late. 

We have reviewed this issue. It is better to keep our code. Because we think it's a safer way to write code that has clear limits rather than wasting gas with unintended calls. If we remove require statement for checking `_to`, there is a case that a message is relayed successfully but the token is not transferred out of L1CrossDomainMessenger.

**Comment by blackcow1987** [comment]
@theo-learner But this is a case where the user inputs `_to` incorrectly, and the token is not transmitted properly even if it is not `messenger`. Is there a reason to check `messenger` separately?

**Comment by theo-learner** [comment]
When it is called from the front-end, it is unlikely that `_to` will be changed to the `messenger`. But I believe that we should check not only the typical cases but also the exceptional ones. As your suggestion, I removed the require statement and tested the case where `_to` is set to the `messenger` when calling `finalizeBridgeNativeToken()`. A revert occurred in `SafeCall.call()`. So the require statement is necessary to check `_to` in advance and prevent the revert case. If the require statement is absent, it will be difficult to avoid gas waste caused by `SafeCall.call()`

call stack:
```bash
    ├─ [14048] L2StandardBridge::finalizeBridgeNativeToken{value: 100}(alice: [0x328809Bc894f92807417D2dAD6b7C998c1aFdac6], L2CrossDomainMessenger: [0x4200000000000000000000000000000000000007], 100, 0x)
    │   ├─ [13532] 0xC0d3c0d3c0D3c0d3C0D3c0D3C0d3C0D3C0D30010::finalizeBridgeNativeToken{value: 100}(alice: [0x328809Bc894f92807417D2dAD6b7C998c1aFdac6], L2CrossDomainMessenger: [0x4200000000000000000000000000000000000007], 100, 0x) [delegatecall]
    │   │   ├─ [0] L2CrossDomainMessenger::xDomainMessageSender() [staticcall]
    │   │   │   └─ ← [Return] L1StandardBridgeProxy: [0xDB25A7b768311dE128BBDa7B8426c3f9C74f3240]
    │   │   ├─ [4924] L2CrossDomainMessenger::fallback{value: 100}()
    │   │   │   ├─ [46] 0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007::fallback{value: 100}() [delegatecall]
    │   │   │   │   └─ ← [Revert] EvmError: Revert
    │   │   │   └─ ← [Revert] EvmError: Revert
    │   │   └─ ← [Revert] revert: StandardBridge: Native token transfer failed
    │   └─ ← [Revert] revert: StandardBridge: Native token transfer failed
    └─ ← [Revert] revert: StandardBridge: Native token transfer failed
```
